site_name: Security Architecture Knowledge Base
docs_dir: docs

nav:
  - Home: index.md
  - Learn:
      - Primer: learn/Primer.md
      - First Principles: learn/FirstPrinciples.md
      - Exercises: learn/Exercises.md
      - Glossary: learn/Glossary.md
  - Patterns:
      - Identity Broker: patterns/IdentityBroker.md
  - Reference Architectures:
      - Zero Trust:
          - Overview: reference/ZeroTrust/Overview.md
          - Diagram: reference/ZeroTrust/Diagram.mmd
          - Controls: reference/ZeroTrust/Controls.md
  - Guides:
      - Azure Bicep: guides/AzureLandingZoneBicep.md
      - AWS CDK: guides/AwsLandingZoneCdk.md
  - Labs:
      - Azure Lab: labs/ZeroTrustAzureBicep/README.md
      - AWS Lab: labs/ZeroTrustAwsCdk/README.md
  - Case Studies:
      - Capital One: case-studies/CapitalOneS3.md
      - K8s RBAC: case-studies/K8sRbacMisconfig.md
      - Insider Abuse: case-studies/InsiderAbuseSaaS.md
  - Compliance:
      - PCI DSS: compliance/PCI_DSS_4_0_Overlay.md
      - NIS2: compliance/NIS2_Overlay.md
      - GDPR: compliance/GDPR_Article32_Overlay.md
      - ISO 27001: compliance/ISO27001_AnnexA_Overlay.md
  - Meta:
      - Roadmap: meta/Roadmap.md
      - Style Guide: meta/StyleGuide.md
      - Changelog: meta/CHANGELOG.md
