site_name: Security Architecture Knowledge Base
docs_dir: docs

nav:
  - Home: index.md
  - Learn:
      - Primer: learn/Primer.md
      - First Principles: learn/FirstPrinciples.md
      - Exercises: learn/Exercises.md
      - Glossary: learn/Glossary.md
  - Patterns: patterns/
  - Reference Architectures:
      - Zero Trust: reference/ZeroTrust/Overview.md
  - Guides: guides/
  - Labs: labs/
  - Case Studies: case-studies/
  - Compliance: compliance/
  - Meta:
      - Roadmap: meta/Roadmap.md
      - Style Guide: meta/StyleGuide.md
      - Changelog: meta/CHANGELOG.md
